/*
 * This source file was generated by the Gradle 'init' task
 */
package sudoku;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        Sudoku classUnderTest = new Sudoku();
    }
}
