/*
 * This source file was generated by the Gradle 'init' task
 */
package sudoku;

public class Sudoku {

    public Grid grid;

    public static void main(String[] args) {
        Sudoku sudoku = new Sudoku();
        sudoku.grid = new Grid(10);
        sudoku.grid.show();
    }
}
